# Generated by Django 3.2.3 on 2021-05-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoomMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sended_datetime', models.DateField(auto_now=True)),
                ('chat_room_name', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=30)),
                ('message', models.CharField(max_length=280)),
            ],
        ),
    ]
