# Generated by Django 3.2.3 on 2021-05-27 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroommessages',
            name='sended_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
